spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: mypassword
  jpa:
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 100
        format_sql: true
        generate_statistics: false
        jdbc:
          time_zone: UTC
        default_schema: acg
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

